# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pre_post_main_v02.ui'
#
# Created: Sun Mar 23 23:50:40 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1141, 517)
        mainWindow.setMaximumSize(QtCore.QSize(1200, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/abouticon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(mainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(250, 120))
        self.pushButton.setStyleSheet(_fromUtf8("border:none;"))
        self.pushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/prepost_logo_01.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(200, 200))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_4.addWidget(self.pushButton)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(250, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.searchSubjectLabel = QtGui.QLabel(self.centralwidget)
        self.searchSubjectLabel.setObjectName(_fromUtf8("searchSubjectLabel"))
        self.verticalLayout_2.addWidget(self.searchSubjectLabel)
        self.searchTagLabel = QtGui.QLabel(self.centralwidget)
        self.searchTagLabel.setObjectName(_fromUtf8("searchTagLabel"))
        self.verticalLayout_2.addWidget(self.searchTagLabel)
        self.searchUserLabel = QtGui.QLabel(self.centralwidget)
        self.searchUserLabel.setObjectName(_fromUtf8("searchUserLabel"))
        self.verticalLayout_2.addWidget(self.searchUserLabel)
        self.searchProjectName = QtGui.QLabel(self.centralwidget)
        self.searchProjectName.setObjectName(_fromUtf8("searchProjectName"))
        self.verticalLayout_2.addWidget(self.searchProjectName)
        self.searchSceneNameLine_2 = QtGui.QLabel(self.centralwidget)
        self.searchSceneNameLine_2.setObjectName(_fromUtf8("searchSceneNameLine_2"))
        self.verticalLayout_2.addWidget(self.searchSceneNameLine_2)
        self.searchSoftwareLine_2 = QtGui.QLabel(self.centralwidget)
        self.searchSoftwareLine_2.setObjectName(_fromUtf8("searchSoftwareLine_2"))
        self.verticalLayout_2.addWidget(self.searchSoftwareLine_2)
        self.searchDateLabel = QtGui.QLabel(self.centralwidget)
        self.searchDateLabel.setObjectName(_fromUtf8("searchDateLabel"))
        self.verticalLayout_2.addWidget(self.searchDateLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.searchSubjectLine = QtGui.QLineEdit(self.centralwidget)
        self.searchSubjectLine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.searchSubjectLine.setObjectName(_fromUtf8("searchSubjectLine"))
        self.verticalLayout.addWidget(self.searchSubjectLine)
        self.searchTagLine = QtGui.QLineEdit(self.centralwidget)
        self.searchTagLine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.searchTagLine.setObjectName(_fromUtf8("searchTagLine"))
        self.verticalLayout.addWidget(self.searchTagLine)
        self.searchUserLine = QtGui.QLineEdit(self.centralwidget)
        self.searchUserLine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.searchUserLine.setObjectName(_fromUtf8("searchUserLine"))
        self.verticalLayout.addWidget(self.searchUserLine)
        self.searchProjectLine = QtGui.QLineEdit(self.centralwidget)
        self.searchProjectLine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.searchProjectLine.setObjectName(_fromUtf8("searchProjectLine"))
        self.verticalLayout.addWidget(self.searchProjectLine)
        self.searchSceneNameLine = QtGui.QLineEdit(self.centralwidget)
        self.searchSceneNameLine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.searchSceneNameLine.setObjectName(_fromUtf8("searchSceneNameLine"))
        self.verticalLayout.addWidget(self.searchSceneNameLine)
        self.searchSoftwareLine = QtGui.QLineEdit(self.centralwidget)
        self.searchSoftwareLine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.searchSoftwareLine.setObjectName(_fromUtf8("searchSoftwareLine"))
        self.verticalLayout.addWidget(self.searchSoftwareLine)
        self.searchDateLine = QtGui.QLineEdit(self.centralwidget)
        self.searchDateLine.setMinimumSize(QtCore.QSize(200, 0))
        self.searchDateLine.setMaximumSize(QtCore.QSize(250, 16777215))
        self.searchDateLine.setObjectName(_fromUtf8("searchDateLine"))
        self.verticalLayout.addWidget(self.searchDateLine)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.mainTable = QtGui.QTableWidget(self.centralwidget)
        self.mainTable.setMinimumSize(QtCore.QSize(800, 0))
        self.mainTable.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.mainTable.setObjectName(_fromUtf8("mainTable"))
        self.mainTable.setSortingEnabled(True)
        self.mainTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.mainTable.setColumnCount(11)
        self.mainTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.mainTable.setHorizontalHeaderItem(10, item)
        self.gridLayout.addWidget(self.mainTable, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_Note = QtGui.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/addnote.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew_Note.setIcon(icon2)
        self.actionNew_Note.setObjectName(_fromUtf8("actionNew_Note"))
        self.actionUpdate_Note = QtGui.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/updatenote.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpdate_Note.setIcon(icon3)
        self.actionUpdate_Note.setObjectName(_fromUtf8("actionUpdate_Note"))
        self.actionRemove_Note = QtGui.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/removenote.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove_Note.setIcon(icon4)
        self.actionRemove_Note.setObjectName(_fromUtf8("actionRemove_Note"))
        self.actionClose = QtGui.QAction(mainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionExport = QtGui.QAction(mainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/exportdata.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon5)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionImport = QtGui.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/importdata.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon6)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionPreference = QtGui.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/setting.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreference.setIcon(icon7)
        self.actionPreference.setObjectName(_fromUtf8("actionPreference"))
        self.actionAbout = QtGui.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon8)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionWiki = QtGui.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/wiki.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWiki.setIcon(icon9)
        self.actionWiki.setObjectName(_fromUtf8("actionWiki"))
        self.menuFile.addAction(self.actionNew_Note)
        self.menuFile.addAction(self.actionUpdate_Note)
        self.menuFile.addAction(self.actionRemove_Note)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionExport)
        self.menuEdit.addAction(self.actionImport)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreference)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionWiki)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew_Note)
        self.toolBar.addAction(self.actionUpdate_Note)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionWiki)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.searchSubjectLine, self.searchTagLine)
        mainWindow.setTabOrder(self.searchTagLine, self.searchUserLine)
        mainWindow.setTabOrder(self.searchUserLine, self.searchProjectLine)
        mainWindow.setTabOrder(self.searchProjectLine, self.searchSceneNameLine)
        mainWindow.setTabOrder(self.searchSceneNameLine, self.searchSoftwareLine)
        mainWindow.setTabOrder(self.searchSoftwareLine, self.searchDateLine)
        mainWindow.setTabOrder(self.searchDateLine, self.pushButton)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "PRE / POST", None))
        self.label_8.setText(_translate("mainWindow", "Search Tool:", None))
        self.searchSubjectLabel.setText(_translate("mainWindow", "Subject", None))
        self.searchTagLabel.setText(_translate("mainWindow", "Tag", None))
        self.searchUserLabel.setText(_translate("mainWindow", "User", None))
        self.searchProjectName.setText(_translate("mainWindow", "Project", None))
        self.searchSceneNameLine_2.setText(_translate("mainWindow", "Scene Name", None))
        self.searchSoftwareLine_2.setText(_translate("mainWindow", "Software", None))
        self.searchDateLabel.setText(_translate("mainWindow", "Date", None))
        item = self.mainTable.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "Subject", None))
        item = self.mainTable.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Description", None))
        item = self.mainTable.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Warnings", None))
        item = self.mainTable.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Scene Name", None))
        item = self.mainTable.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Date", None))
        item = self.mainTable.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Time", None))
        item = self.mainTable.horizontalHeaderItem(6)
        item.setText(_translate("mainWindow", "Software", None))
        item = self.mainTable.horizontalHeaderItem(7)
        item.setText(_translate("mainWindow", "User", None))
        item = self.mainTable.horizontalHeaderItem(8)
        item.setText(_translate("mainWindow", "New Column", None))
        item = self.mainTable.horizontalHeaderItem(9)
        item.setText(_translate("mainWindow", "Images", None))
        item = self.mainTable.horizontalHeaderItem(10)
        item.setText(_translate("mainWindow", "Project Name", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("mainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar", None))
        self.actionNew_Note.setText(_translate("mainWindow", "New Note", None))
        self.actionUpdate_Note.setText(_translate("mainWindow", "Update Note", None))
        self.actionRemove_Note.setText(_translate("mainWindow", "Remove Note", None))
        self.actionClose.setText(_translate("mainWindow", "Close", None))
        self.actionExport.setText(_translate("mainWindow", "Export", None))
        self.actionImport.setText(_translate("mainWindow", "Import", None))
        self.actionPreference.setText(_translate("mainWindow", "Preference", None))
        self.actionAbout.setText(_translate("mainWindow", "About", None))
        self.actionWiki.setText(_translate("mainWindow", "Wiki", None))

from media import resource_rc
